### ISSUE TITLE
How to interpret the Velocity?

### ISSUE THREAD

**Issue by selvarajan31** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#21]
Hi,
I'm using `AWR1642 EVM` to detect obstacles. I was using Demo Visualizer to evaluate the range and velocity. In the Demo Visualizer, the velocity will be negative if the obstacle move towards the sensor (please check the image) and positive if the obstacle moves away. But, I was not able to obtain an accurate value. So I started using your python code.

![Screenshot from 2021-03-27 13-55-48](https://user-images.githubusercontent.com/41108566/112717124-90694980-8f10-11eb-9f86-fd50cfbbe286.png)

While using, I analyzed that, sometimes the velocity is both positive and negative when the obstacle is approaching towards the sensor. How to interpret such difference? I needed the positivity and negativity to differentiate the moving direction of the obstacle.
Please help me with the issue.

Thanks in advance
Selvarajan Nagendran

**Comment by ibaiGorordo** [comment]
Are you using the same configuration in both cases? The python code should return the same velocity as the demo visualizer, particularly in the SDK 3, the radar sends the velocity directly in m/s, and since there aren't any calculations necessary (compared to previous SDK versions) there aren't many options to make mistakes in the calculations.

If you are not doing it already, I would recommend to use a different configuration than the one in this repository. I made it mainly for very short range detections and didn't care much about the velocity.
