### ISSUE TITLE
AWR1642BOOST EVM -- STATIC CLUTTER REMOVAL

### ISSUE THREAD

**Issue by guruvishnuvardan** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#27]
![PXL_20210925_083357041](https://user-images.githubusercontent.com/31349523/136723963-7440640e-958a-4c9b-ae71-c8de210cfd6f.jpg)
Hi @ibaiGorordo 

Good Day!

Please find the attached image(displaying the position where the radar is fixed in a Car), While testing the radar, I  encountered noise data from irregular road plane  / tiny pot holes.

If I enable the static clutter, Can I be able to reduce the above said noise data? Or Can I tilt the radar upwards to avoid the radar signals hitting the road (at least for time being, as I couldn't find a way to control elevation data in AWR1642BOOST EVM)

Thanks
Guru

**Comment by ibaiGorordo** [comment]
The clutter removal is probably not going to work in your case, because even though those things are static, since the car is moving, those objects will not have a zero velocity (therefore the clutter removal will probably fail).

You can either rotate the radar, or since you know the angle and the height of the radar, you could filter out the points in the postprocessing.

Btw, are you planning to combine the radar points with the camera?

**Comment by guruvishnuvardan** [comment]
Hi Ibai,

Yes, AWR1642BOOST gives elevation data, but folks from TI said, it can not be controlled, as TX and RX are in the same plane.

We are working to Simulate Short Distance Obstacle Detection (From 2 meters to 50 Meters), that's why I was preferring ODS, as you have suggested, I will try purchasing AWR1843BOOST, using that I will control the distance to 50 Meters (though it can detect longer ranges)

Thanks
Guru
