### ISSUE TITLE
issues with QtGui.Application()

### ISSUE THREAD

**Issue by 89cgu** [ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-#8]
Hi, I'm unsure if this is the right place to ask this question,

At line 281 of readData_AWR1843.py file. When the GUI launches, the entire GUI crashes straight away, but the rest of the code still runs through the debugger. I've also tried using the AWR1642 readData file and it does the same thing. I can't seem to find any documentation online and im struggling to run the program. Some direction would be greatly appreciated.

**Comment by ibaiGorordo** [comment]
Hi,

To be honest I am not expert with the PyQtGraph library, so, I have no idea what might be the problem. Probably you already tried, but try to uninstall and install the PyQtGraph and PyQt libraries. Also, what Python version are you using?

You can also check the PyQtGraph repository: https://github.com/pyqtgraph/pyqtgraph

If nothing works, then you can remove the PyQtGraph functions and use matplotlib. The problem is that the plots will not be fast.

Let me know how it goes
Ibai
